### PR TITLE
Add support for client provided headers and cookies

### PR DESCRIPTION
**Pull request by sam-ulrich1**
Adds support for arbitrary headers and cookies provided to the client

Updated tests to validate the change.

### CODE REVIEW

**Comment by aler9** [comment]
Hello, this feature can be implemented in a shorter and more versatile way by adding a callback called `OnRequest`:

```go
// called before every request
OnRequest func(*http.Request)
```

This allows to edit anything in the request and furthermore it allows selective editing by using any field of the existing request. This is already implemented inside [gortsplib](https://pkg.go.dev/github.com/bluenviron/gortsplib/v4#Client).

Therefore: if you remove `Headers` and `Cookie` and instead add `OnRequest`, this can be merged.

**Comment by sam-ulrich1** [comment]
I have a lot of other changes like supporting compression and faster than presentation time downloading/decoding. If you're open to my code changes then I'll offer them but I'm not particularly interested in redoing the work to your spec. No offense just don't have much spare time

**Comment by aler9** [comment]
@sam-ulrich1 in all open source projects, improvements are welcome but they must provide a common benefits and adhere to standards. Every additional line of code is an additional maintenance burden. Additions to public APIs are particularly critical since once accepted they become part of the documentation and cannot be reverted unless a new breaking version is released.

This is hard for everyone, and that's the reason why there are small and big companies that are paying other open source projects for skipping this process and merging specific integrations, sometimes with their name on it, but personally i don't think this is the right approach, since the code becomes unmanageable.

Therefore: if you want to get your code merged, just perform required changes, so no one will ever need to hack the library in order to change a field of a request.

**Comment by sam-ulrich1** [comment]
Totally understand. Just don't have the time to do a rework for the sake of a merge

**Comment by aler9** [comment]
replaced by #163

**Pull request closed without merging**
